preload = /etc/nixos/resources/wallpapers/main.png
wallpaper = ,/etc/nixos/resources/wallpapers/main.png
preload = /etc/nixos/resources/wallpapers/main.jpg
wallpaper = ,/etc/nixos/resources/wallpapers/main.jpg

ipc = off
splash = false
