
# wallpaper {
#     monitor =  # All monitors
#     path = /etc/nixos/resources/wallpapers/choices/BlackHole.png
#     fit_mode = cover # You can also use 'fill' or 'contain'
# }

wallpaper {
    monitor =  # All monitors
    path = /etc/nixos/resources/wallpapers/Forest.png
    fit_mode = cover # You can also use 'fill' or 'contain'
}

# wallpaper {
#     monitor =  # All monitors
#     path = /etc/nixos/resources/wallpapers/MoonAndSat.jpg
#     fit_mode = cover # You can also use 'fill' or 'contain'
# }

# wallpaper {
#     monitor =  # All monitors
#     path = /etc/nixos/resources/wallpapers/Acebee2.png
#     fit_mode = cover # You can also use 'fill' or 'contain'
# }
# wallpaper {
#     monitor =  # All monitors
#     path = /etc/nixos/resources/wallpapers/preview.jpg
#     fit_mode = cover # You can also use 'fill' or 'contain'
# }

splash = false 



