preload = /etc/nixos/resources/wallpapers/main.png
wallpaper = ,/etc/nixos/resources/wallpapers/main.png
preload = /etc/nixos/resources/wallpapers/main.jpg
wallpaper = ,/etc/nixos/resources/wallpapers/main.jpg
preload = /etc/nixos/resources/wallpapers/main.jpeg
wallpaper = ,/etc/nixos/resources/wallpapers/main.jpeg
preload = /etc/nixos/resources/wallpapers/space.png
wallpaper = ,/etc/nixos/resources/wallpapers/space.png
ipc = off
splash = false
