keys:
  - &higgs_boson age1zfmfjmyx5w59dv330qnguapkc6rf6nhrzx6w0067vwfxql894f3sl80p8c

creation_rules:
  - path_regex: secrets/.*$
    key_groups:
      - age:
        - *higgs_boson
        # - *gluon