# .sops.yaml
keys:
  - &higgs_boson "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOUcboE1pZNsnmrayLWiNiYuSvP+wO6O9irjRlOjmNFN root@nixos"
  
  # - &gluon "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI...<insert gluon pub key here>"

creation_rules:
  # Any file in the secrets directory will be encrypted for both machines
  - path_regex: secrets/.*$
    key_groups:
      - age:
        - *higgs_boson
        # - *gluon