
{ config, pkgs, inputs, ... }:

{
    imports = [
        ./hardware-configuration.nix
        # ./user.nix

        # All of the modules I have
        ../modules/programs/programs.nix
        ../modules/boot/boot.nix
        ../modules/network/network.nix
        ../modules/syncthing/syncthing.nix
        ../modules/virtualization/virtualMachines.nix
        ../modules/platformIO/pio.nix
    ];

    nixpkgs.overlays = [ (import ./overlays/kitty-fix.nix) ];


    nix.settings.experimental-features = [ "nix-command" "flakes" ];
    networking.hostName = "higgs-boson";
    

    # Main config stuff that shouldn't really change
    i18n.defaultLocale = "en_US.UTF-8";
    time.timeZone = "America/Chicago";
    services.xserver.enable = true;
    nixpkgs.config.allowUnfree = true; 

    ############
    # Firewall #
    ############
    # Allowing certain things through the firewall
    networking.firewall = {
        enable = true;
        allowedTCPPortRanges = [
            { from = 1714; to = 1764; }  # KDE Connect
            { from = 22; to = 22; }      # SSH
        ];
        allowedUDPPortRanges = [
            { from = 1714; to = 1764; }  # KDE Connect
        ];
    }; 

    # Don't touch (tldr of what the autogenerated comment said)
    system.stateVersion = "23.11";   

}