[pyprland]
plugins = [
  "scratchpads",
  "magnify",
  "expose",
  "shortcuts_menu",
  "toggle_special",
]


[scratchpads.term]
animation = "fromTop"
command = "kitty --class kit-term"
class = "kit-term"
size = "75% 60%"
lazy = true

[scratchpads.volume]
command = "pavucontrol"
animation = "fromLeft"
class = "volume_sidemenu"
size = "40% 70%"
unfocus = "hide"
excludes = "*"
lazy = true
margin = 90
multi = false



