# { config, pkgs, inputs, lib, ... }:

# {
#   imports = [
#     ./hardware-configuration.nix
#   ];

#   nix.settings.experimental-features = [ "nix-command" "flakes" ];
#   networking.hostName = "gluon";

#   # Me :D
#   users.users = {
#     sa9m = {
#       isNormalUser = true;
#       extraGroups = [ "wheel" "networkmanager" "audio" "dialout" "plugdev" "docker" "input" "uinput" ];
#     };
#   };

#   # Main config stuff that shouldn't really change
#   i18n.defaultLocale = "en_US.UTF-8";
#   time.timeZone = "America/Chicago";
#   services.xserver.enable = true;
#   nixpkgs.config.allowUnfree = true;
#   networking.firewall = {
#     enable = true;
#   };
#   boot.loader.grub.device = "nodev";
#   environment.pathsToLink = [
#     "/share/xdg-desktop-portal"
#     "/share/applications"
#   ];

#   # Upgrading to the most recent kernel 
#   boot.kernelPackages = pkgs.linuxPackages_latest;

#   # Adding swap so that I can hibernate
#   swapDevices = [
#     {
#       device = "/var/lib/swapfile";
#       size = 16 * 1024; # 16GB
#     }
#   ];
#   boot.initrd.systemd.enable = true;


#   # Don't touch (tldr of what the autogenerated comment said)
#   system.stateVersion = "26.05";


# }
{ config, pkgs, inputs, ... }:

# Note to self: to edit secrets, run `sops secrets/secrets.yaml`

{
  imports = [
    ./hardware-configuration.nix
  ];

  # Me :D
  users.users = {
    sa9m = {
      isNormalUser = true;
      extraGroups = [ "wheel" "networkmanager" "audio" "dialout" "plugdev" "docker" "input" "uinput" ];
    };
  };

  # Main config stuff that shouldn't really change
  i18n.supportedLocales = [
    "en_US.UTF-8/UTF-8"
  ];
  time.timeZone = "America/Chicago";
  services.xserver.enable = true;
  nixpkgs.config.allowUnfree = true;
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  networking.hostName = "gluon";
  boot.kernelPackages = pkgs.linuxPackages_testing;
  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 16 * 1024; # 16GB
    }
  ];
  # boot.kernelParams = [
  #   "resume=UUID=606544fb-61ec-4f34-99fe-b9dde180c05e"
  #   "resume_offset=116987904"
  #   "usbhid.quirks=0x04f3:0c00:0x0040"
  # ];
  # boot.resumeDevice = "/dev/disk/by-uuid/606544fb-61ec-4f34-99fe-b9dde180c05e";
  boot.loader.grub.device = "nodev";
  environment.pathsToLink = [
    "/share/xdg-desktop-portal"
    "/share/applications"
  ];

  # I use the noctalia lockscreen, so I can skip the sddm
  services.displayManager.autoLogin = {
    enable = true;
    user = "sa9m";
  };
  services.displayManager.defaultSession = "hyprland-uwsm";

  # Will likely be moved to a module tbh
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
    settings = {
      General = {
        Experimental = true;
        FastConnectable = true;
      };
      Policy = {
        AutoEnable = true;
      };
    };
  };

  hardware.enableAllFirmware = true;
  # Might add a wifi module, but this is here for now instead
  networking.networkmanager.enable = true;
  environment.systemPackages = [
    pkgs.networkmanagerapplet
  ];

  # Don't touch (tldr of what the autogenerated comment said)
  system.stateVersion = "23.11";

  # TODO move to a module
  # Udev rules for the pico 
  services.udev.extraRules = ''
    # Raspberry Pi Pico (Bootloader Mode)
    SUBSYSTEM=="usb", ATTRS{idVendor}=="2e8a", ATTRS{idProduct}=="0003", MODE="0666"
    
    # Raspberry Pi Debug Probe (CMSIS-DAP)
    SUBSYSTEM=="usb", ATTRS{idVendor}=="2e8a", ATTRS{idProduct}=="000c", MODE="0666"
    
    # Generic CMSIS-DAP probes (if you use a different debugger)
    SUBSYSTEM=="usb", ATTRS{idVendor}=="c251", ATTRS{idProduct}=="f000", MODE="0666"
  '';

  programs.hyprland.enable = true;

}
