{ config, pkgs, inputs, lib, ... }:

{
  imports = [
    ./hardware-configuration.nix
    # ./user.nix

    # All of the modules I have
    ../../modules/programs/programs.nix
    ../../modules/boot/boot.nix
    ../../modules/boot/grub.nix
    ../../modules/network/network.nix
    ../../modules/syncthing/syncthing.nix
    ../../modules/virtualization/virtualMachines.nix
    ../../modules/platformIO/pio.nix
    # ../../modules/rclone/rclone.nix # Commented until we add in the gluon key
    ../../modules/drive/drive.nix
    # ../../modules/google-drive/google-drive.nix
    ../../modules/hyprland/hyprland.nix
    ../../modules/theme/theme.nix
    ../../modules/theme/fonts.nix
    ../../modules/nordvpn/minimalWgnord.nix
    ../../modules/atuin/atuin.nix
    ../../modules/rgb/openrgb.nix
    ../../modules/brightness/pc-brightness.nix
    ../../modules/emacs/emacs.nix
    ../../modules/school/mathematica.nix
    ../../modules/gaming/sunshine.nix


  ];

  # nixpkgs.overlays = [ (import ../../overlays/kitty.nix) ];
  # DEBUG: Define the kitty overlay inline to bypass any pathing issues.
  nixpkgs.overlays = [
    (final: prev: {
      kitty = prev.kitty.overrideAttrs (oldAttrs: {
        # This is a more aggressive way to skip tests by replacing
        # the entire phase with a command that does nothing.
        installCheckPhase = ''
          echo "Skipping failing kitty tests."
        '';
      });
    })
    (final: prev: {
      winboat = inputs.winboat.packages.${pkgs.stdenv.hostPlatform.system}.winboat;
    })
  ];

  # So that it automatically opens Windows instead of linux (Just for now)
  boot.loader.grub.default = "Windows Boot Manager (on /dev/nvme0n1p1)";

  # Just trying to get it to work
  hardware.enableRedistributableFirmware = true;
  services.dbus.implementation = pkgs.lib.mkForce "dbus";

  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  networking.hostName = "gluon";

  # Me :D
  users.users = {
    sa9m = {
      isNormalUser = true;
      extraGroups = [ "wheel" "networkmanager" "audio" "dialout" "plugdev" "docker" "input" "uinput" ];
      shell = pkgs.fish;
    };
  };

  # Telling the computer that the bluetooth thingy does a weird thing sometimes 
  boot.kernelParams = [ "btusb.enable_autosuspend=n" ];
  boot.blacklistedKernelModules = [ "btintel" ]; # Force it not to try Intel drivers


  # Main config stuff that shouldn't really change
  i18n.defaultLocale = "en_US.UTF-8";
  time.timeZone = "America/Chicago";
  services.xserver.enable = true;
  nixpkgs.config.allowUnfree = true;

  ############
  # Firewall #
  ############
  # Allowing certain things through the firewall
  networking.firewall = {
    enable = true;
    checkReversePath = "loose";
    trustedInterfaces = [ "wgnord" ];
    allowedTCPPortRanges = [
      { from = 1714; to = 1764; } # KDE Connect
      { from = 1194; to = 1194; } # NordVPN
      { from = 22; to = 22; } # SSH
    ];
    allowedUDPPortRanges = [
      { from = 1714; to = 1764; } # KDE Connect
      { from = 443; to = 443; } # NordVPN
      { from = 32768; to = 60999; } # Chromecast
    ];
  };

  # Upgrading to the most recent kernel 
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # Adding swap so that I can hibernate
  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 16 * 1024; # 16GB
    }
  ];
  boot.initrd.systemd.enable = true;


  # Adding in fonts for my code editors
  fonts.packages = with pkgs; [
    nerd-fonts.jetbrains-mono
    nerd-fonts.symbols-only
    noto-fonts
    nerd-fonts.noto
  ];

  # Allowing me to run reboot without a password
  security.sudo.extraRules = [
    {
      users = [ "yourusername" ];
      commands = [
        {
          command = "/run/current-system/sw/bin/reboot";
          options = [ "NOPASSWD" ];
        }
        {
          command = "/run/current-system/sw/bin/grub-reboot";
          options = [ "NOPASSWD" ];
        }
      ];
    }
  ];

  # Funy
  environment.systemPackages = [
    pkgs.quartus-prime-lite
  ];

  # Don't touch (tldr of what the autogenerated comment said)
  system.stateVersion = "23.11";

}
