{ config, pkgs, inputs, lib, ... }:

{
  imports = [
    ./hardware-configuration.nix
  ];

  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  networking.hostName = "gluon";

  # Me :D
  users.users = {
    sa9m = {
      isNormalUser = true;
      extraGroups = [ "wheel" "networkmanager" "audio" "dialout" "plugdev" "docker" "input" "uinput" ];
      shell = pkgs.fish;
    };
  };

  # Main config stuff that shouldn't really change
  i18n.defaultLocale = "en_US.UTF-8";
  time.timeZone = "America/Chicago";
  services.xserver.enable = true;
  nixpkgs.config.allowUnfree = true;

  ############
  # Firewall #
  ############
  # Allowing certain things through the firewall
  networking.firewall = {
    enable = true;
  };

  # Upgrading to the most recent kernel 
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # Adding swap so that I can hibernate
  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 16 * 1024; # 16GB
    }
  ];
  boot.initrd.systemd.enable = true;


  # Don't touch (tldr of what the autogenerated comment said)
  system.stateVersion = "26.05";


}
