{ config, pkgs, inputs, ... }:

{
  imports = [
    ./hardware-configuration.nix
    # ./user.nix

    # All of the modules I have
    ../../modules/programs/programs.nix
    ../../modules/boot/boot.nix
    ../../modules/network/network.nix
    ../../modules/syncthing/syncthing.nix
    ../../modules/virtualization/virtualMachines.nix
    ../../modules/platformIO/pio.nix
    # ../../modules/rclone/rclone.nix # Removed because it was making my file picker excruciatingly slow
    ../../modules/drive/drive.nix
    # ../../modules/google-drive/google-drive.nix
    ../../modules/hyprland/hyprland.nix
    ../../modules/theme/theme.nix
    ../../modules/theme/fonts.nix
    ../../modules/nordvpn/minimalWgnord.nix
    ../../modules/atuin/atuin.nix
    ../../modules/rgb/openrgb.nix
    ../../modules/emacs/emacs.nix

  ];

  # nixpkgs.overlays = [ (import ../../overlays/kitty.nix) ];
  # DEBUG: Define the kitty overlay inline to bypass any pathing issues.
  nixpkgs.overlays = [
    (final: prev: {
      kitty = prev.kitty.overrideAttrs (oldAttrs: {
        # This is a more aggressive way to skip tests by replacing
        # the entire phase with a command that does nothing.
        installCheckPhase = ''
          echo "Skipping failing kitty tests."
        '';
      });
    })
    (final: prev: {
      winboat = inputs.winboat.packages.${pkgs.stdenv.hostPlatform.system}.winboat;
    })
  ];

  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  networking.hostName = "higgs-boson";

  # Me :D
  users.users = {
    sa9m = {
      isNormalUser = true;
      extraGroups = [ "wheel" "networkmanager" "audio" "dialout" "plugdev" "docker" "input" "uinput" ];
      shell = pkgs.fish;
    };
  };


  # Main config stuff that shouldn't really change
  i18n.defaultLocale = "en_US.UTF-8";
  time.timeZone = "America/Chicago";
  services.xserver.enable = true;
  nixpkgs.config.allowUnfree = true;

  ############
  # Firewall #
  ############
  # Allowing certain things through the firewall
  networking.firewall = {
    enable = true;
    checkReversePath = "loose";
    trustedInterfaces = [ "wgnord" ];
    allowedTCPPortRanges = [
      { from = 1714; to = 1764; } # KDE Connect
      { from = 1194; to = 1194; } # NordVPN
      { from = 22; to = 22; } # SSH
    ];
    allowedUDPPortRanges = [
      { from = 1714; to = 1764; } # KDE Connect
      { from = 443; to = 443; } # NordVPN
      { from = 32768; to = 60999; } # Chromecast
    ];
  };

  # Upgrading to the most recent kernel 
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # Adding in extra swap so that hibernation works
  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 16 * 1024; # 16GB
    }
  ];
  boot.kernelParams = [
    "resume=UUID=606544fb-61ec-4f34-99fe-b9dde180c05e"
    "resume_offset=116987904"
  ];
  boot.resumeDevice = "/dev/disk/by-uuid/606544fb-61ec-4f34-99fe-b9dde180c05e";

  # Don't touch (tldr of what the autogenerated comment said)
  system.stateVersion = "23.11";

  # TODO move to a module
  # Udev rules for the pico 
  services.udev.extraRules = ''
    # Raspberry Pi Pico (Bootloader Mode)
    SUBSYSTEM=="usb", ATTRS{idVendor}=="2e8a", ATTRS{idProduct}=="0003", MODE="0666"
    
    # Raspberry Pi Debug Probe (CMSIS-DAP)
    SUBSYSTEM=="usb", ATTRS{idVendor}=="2e8a", ATTRS{idProduct}=="000c", MODE="0666"
    
    # Generic CMSIS-DAP probes (if you use a different debugger)
    SUBSYSTEM=="usb", ATTRS{idVendor}=="c251", ATTRS{idProduct}=="f000", MODE="0666"
  '';

  # Adding in fonts for my code editors
  # fonts.packages = with pkgs; [
  #   nerd-fonts.jetbrains-mono
  #   nerd-fonts.symbols-only
  #   noto-fonts
  # ];


}
