{ config, pkgs, inputs, ... }:

# Note to self: to edit secrets, run `sops secrets/secrets.yaml`

{
  imports = [
    ./hardware-configuration.nix
    # ./user.nix

    # All of the modules I have
    ../../modules/programs/programs.nix
    ../../modules/kde/kde.nix
    ../../modules/programs/man-cache.nix
    ../../modules/boot/boot.nix
    ../../modules/boot/grub.nix
    ../../modules/network/network.nix
    ../../modules/syncthing/syncthing.nix
    ../../modules/virtualization/virtualMachines.nix
    ../../modules/platformIO/pio.nix
    ../../modules/rclone/rclone.nix # Added back in but limited to just NAS
    ../../modules/drive/drive.nix
    # ../../modules/google-drive/google-drive.nix # Also removed beccause it made it slow
    ../../modules/hyprland/hyprland.nix
    ../../modules/theme/theme.nix
    ../../modules/theme/fonts.nix
    ../../modules/nordvpn/minimalWgnord.nix
    ../../modules/atuin/atuin.nix
    ../../modules/rgb/openrgb.nix
    ../../modules/emacs/emacs.nix
    ../../modules/random-cool-stuff/alien.nix
    ../../modules/school/mathematica.nix
    ../../modules/gaming/moonlight.nix
    # ../../modules/keyboard/steno.nix # Removed because I could lock my computer with it on and not be able to sign in 

  ];

  # nixpkgs.overlays = [ (import ../../overlays/kitty.nix) ];
  # TODO Move this to it's own module
  nixpkgs.overlays = [
    (final: prev: {
      kitty = prev.kitty.overrideAttrs (oldAttrs: {
        # This is a more aggressive way to skip tests by replacing
        # the entire phase with a command that does nothing.
        installCheckPhase = ''
          echo "Skipping failing kitty tests."
        '';
      });
    })
    (final: prev: {
      winboat = inputs.winboat.packages.${pkgs.stdenv.hostPlatform.system}.winboat;
    })
  ];

  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  networking.hostName = "higgs-boson";

  # Me :D
  users.users = {
    sa9m = {
      isNormalUser = true;
      extraGroups = [ "wheel" "networkmanager" "audio" "dialout" "plugdev" "docker" "input" "uinput" ];
      shell = pkgs.fish;
    };
  };


  # Main config stuff that shouldn't really change
  i18n.supportedLocales = [
    "en_US.UTF-8/UTF-8"
    "en_CA.UTF-8/UTF-8" # Add this to fix the perl warnings
  ];
  time.timeZone = "America/Chicago";
  services.xserver.enable = true;
  nixpkgs.config.allowUnfree = true;

  ############
  # Firewall #
  ############
  networking.firewall = {
    enable = true;
    checkReversePath = "loose";
    trustedInterfaces = [ "wgnord" ];
    allowedTCPPortRanges = [
      { from = 1714; to = 1764; } # KDE Connect
      { from = 1194; to = 1194; } # NordVPN
      { from = 22; to = 22; } # SSH
      { from = 25565; to = 25565; } # Minecraft
      { from = 36891; to = 36891; } # Minecraft
      { from = 8008; to = 8009; } # Chromecast
    ];
    allowedUDPPortRanges = [
      { from = 1714; to = 1764; } # KDE Connect
      { from = 443; to = 443; } # NordVPN
      { from = 32768; to = 60999; } # Chromecast
    ];
  };

  # Upgrading to the most recent kernel 
  boot.kernelPackages = pkgs.linuxPackages_testing;

  # Adding in extra swap so that hibernation works
  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 16 * 1024; # 16GB
    }
  ];
  boot.kernelParams = [
    "resume=UUID=606544fb-61ec-4f34-99fe-b9dde180c05e"
    "resume_offset=116987904"
  ];
  boot.resumeDevice = "/dev/disk/by-uuid/606544fb-61ec-4f34-99fe-b9dde180c05e";

  # Don't touch (tldr of what the autogenerated comment said)
  system.stateVersion = "23.11";

  # TODO move to a module
  # Udev rules for the pico 
  services.udev.extraRules = ''
    # Raspberry Pi Pico (Bootloader Mode)
    SUBSYSTEM=="usb", ATTRS{idVendor}=="2e8a", ATTRS{idProduct}=="0003", MODE="0666"
    
    # Raspberry Pi Debug Probe (CMSIS-DAP)
    SUBSYSTEM=="usb", ATTRS{idVendor}=="2e8a", ATTRS{idProduct}=="000c", MODE="0666"
    
    # Generic CMSIS-DAP probes (if you use a different debugger)
    SUBSYSTEM=="usb", ATTRS{idVendor}=="c251", ATTRS{idProduct}=="f000", MODE="0666"
  '';

  # Adding in fonts for my code editors
  fonts.packages = with pkgs; [
    nerd-fonts.jetbrains-mono
    nerd-fonts.symbols-only
    noto-fonts
    nerd-fonts.noto
  ];

  # So that I can use direnv to make better nix dev shells
  programs.direnv.enable = true;
  programs.direnv.nix-direnv.enable = true;

  services.avahi = {
    enable = true;
    nssmdns4 = true;
    openFirewall = true;
  };


  # Telling sops where to find the secrets
  sops.defaultSopsFile = ../../secrets/secrets.yaml;
  sops.defaultSopsFormat = "yaml";



}
