{ config, pkgs, inputs, ... }:

# Note to self: to edit secrets, run `sops secrets/secrets.yaml`

{
  imports = [
    ./hardware-configuration.nix
    ../../Modules/Hyprland/system.nix
    ../../Modules/Steam/system.nix
    ../../Modules/TLP/system.nix
    ../../Modules/Tailscale/system.nix
    ../../Modules/KDE-Connect/system.nix
    ../../Modules/Syncthing/system.nix
  ];

  # Me :D
  users.users = {
    sa9m = {
      isNormalUser = true;
      extraGroups = [ "wheel" "networkmanager" "audio" "dialout" "plugdev" "docker" "input" "uinput" ];
    };
  };

  # Main config stuff that shouldn't really change
  i18n.supportedLocales = [
    "en_US.UTF-8/UTF-8"
  ];
  time.timeZone = "America/Chicago";
  services.xserver.enable = true;
  nixpkgs.config.allowUnfree = true;
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  networking.hostName = "higgs-boson";
  boot.kernelPackages = pkgs.linuxPackages_testing;
  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 16 * 1024; # 16GB
    }
  ];
  boot.kernelParams = [
    "resume=UUID=606544fb-61ec-4f34-99fe-b9dde180c05e"
    "resume_offset=116987904"
    "usbhid.quirks=0x04f3:0c00:0x0040"
  ];
  boot.loader.grub = {
    enable = true;
    default = "saved";
    useOSProber = true;


    efiSupport = true;
    device = "nodev";
  };
  boot.resumeDevice = "/dev/disk/by-uuid/606544fb-61ec-4f34-99fe-b9dde180c05e";
  environment.pathsToLink = [
    "/share/xdg-desktop-portal"
    "/share/applications"
  ];


  # Will likely be moved to a module tbh
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
    settings = {
      General = {
        Experimental = true;
        FastConnectable = true;
      };
      Policy = {
        AutoEnable = true;
      };
    };
  };

  # To allow things to run stuff by downloading from the internet
  programs.nix-ld.enable = true;

  services.displayManager.autoLogin = {
    enable = true;
    user = "sa9m";
  };
  services.displayManager.defaultSession = "hyprland-uwsm";

  hardware.enableAllFirmware = true;
  # Might add a wifi module, but this is here for now instead
  networking.networkmanager.enable = true;
  environment.systemPackages = [
    pkgs.networkmanagerapplet
  ];

  # Don't touch (tldr of what the autogenerated comment said)
  system.stateVersion = "23.11";

  # TODO move to a module
  # Udev rules for the pico 
  services.udev.extraRules = ''
    # Raspberry Pi Pico (Bootloader Mode)
    SUBSYSTEM=="usb", ATTRS{idVendor}=="2e8a", ATTRS{idProduct}=="0003", MODE="0666"
    
    # Raspberry Pi Debug Probe (CMSIS-DAP)
    SUBSYSTEM=="usb", ATTRS{idVendor}=="2e8a", ATTRS{idProduct}=="000c", MODE="0666"
    
    # Generic CMSIS-DAP probes (if you use a different debugger)
    SUBSYSTEM=="usb", ATTRS{idVendor}=="c251", ATTRS{idProduct}=="f000", MODE="0666"
  '';


  programs.hyprland.enable = true;

  # TODO move to SSH-host module
  services.openssh = {
    enable = true;
    openFirewall = true;
  };

}
