exec-once = sh -c '
HOST=$(hostname)
if [ "$HOST" = "gluon" ]; then
  echo "source = dotfiles/hypr/host-specific/gluon.conf" > /tmp/hypr-host.conf
else if [ "$HOST" = "higgs-boson" ]
  echo "source = dotfiles/hypr/host-specific/higgs-boson.conf" > /tmp/hypr-host.conf
fi
'
source = /tmp/hypr-host.conf
