# This is where all of the modules that I want are imported, regardless of host
{ config
, pkgs
, lib
, inputs
, username
, ...
}:
{

  # My modules
  imports = [
    # Programs to download/use
    ../Modules/OpenRGB/default.nix
    ../Modules/Fish/default.nix
    ../Modules/Hyprland/default.nix
    ../Modules/Hypridle/default.nix
    ../Modules/Spotify/default.nix
    ../Modules/Obsidian/default.nix
    ../Modules/KDE-Connect/default.nix
    ../Modules/Funny/default.nix
    ../Modules/NVim/default.nix
    ../Modules/Wgnord/default.nix
    # ../Modules/Hyprland/default.nix
    ../Modules/Steam/default.nix
    ../Modules/Tailscale/default.nix
    ../Modules/Droidcam/default.nix
    ../Modules/Syncthing/default.nix
    ../Modules/KDE-Connect/default.nix
    # ../Modules/Streamio/default.nix # currently installed through flatpak
    # Resource movement
    ./../Resources/Profile/profile.nix
    ./../Resources/Wallpaper/wallpaper.nix
  ];

  # Me :D
  users.users.${username} = {
    isNormalUser = true;
    extraGroups = [
      "wheel"
      "networkmanager"
      "audio"
      "dialout"
      "plugdev"
      "docker"
      "input"
      "uinput"
    ];
  };

  # Random stuff that generally needs to be here
  i18n.supportedLocales = [
    "en_US.UTF-8/UTF-8"
  ];
  time.timeZone = "America/Chicago";
  services.xserver.enable = true;
  nixpkgs.config.allowUnfree = true;
  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];
  boot.kernelPackages = pkgs.linuxPackages_testing;
  fonts.fontconfig.antialias = true;

  # I use the noctalia lockscreen, so I can skip the sddm
  services.displayManager.autoLogin = {
    enable = true;
    user = username;
  };
  services.displayManager.defaultSession = "hyprland-uwsm";

  # For wireless stuff
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
    settings = {
      General = {
        Experimental = true;
        FastConnectable = true;
      };
      Policy = {
        AutoEnable = true;
      };
    };
  };
  hardware.enableAllFirmware = true;
  networking.networkmanager.enable = true;
  environment.systemPackages = [
    pkgs.networkmanagerapplet
  ];
  networking.nameservers = [
    "1.1.1.1"
    "8.8.8.8"
  ];

  # To allow things to run stuff by downloading from the internet
  programs.nix-ld.enable = true;

  # Things that I either haven't put into a module yet or make sense to always be imported
  home-manager.users.${username} =
    { config, ... }:
    {
      home.packages = with pkgs; [
        brave
        vscode
        discord
        kdePackages.dolphin
        nixpkgs-fmt
        nom
        slurp
        grim
        wl-clipboard
        kicad
        nh
        hyfetch
        fastfetch

        zoom-us
        ubase
        kdePackages.ark
        unzip
        libreoffice
        stm32cubemx
        openrgb
        # rustdesk-flutter
        jellyfin-desktop
        fetch
        packet

        pavucontrol # This will likely get moved to hyprland so that I can have it automatically pop up in a special workspace when I want it
        overskride # Same thing with things like bluetooth, which I believe is like Overskride

        # TODO move
        kicad
        github-desktop

        # DEBUG TODO REMOVE
        libnotify
        droidcam
        adb-sync
        v4l-utils
        android-tools
      ];

      # My basic git configuration which I will always want on my system
      programs.git = {
        enable = true;
        settings.user.name = "Sa9m";
        settings.user.email = "abyssalflerken@gmail.com";
      };

      home.stateVersion = "26.05";

    };

  # Don't touch (tldr of what the autogenerated comment said)
  system.stateVersion = "23.11";

  # TODO move to a module
  # Udev rules for the pico
  services.udev.extraRules = ''
    # Raspberry Pi Pico (Bootloader Mode)
    SUBSYSTEM=="usb", ATTRS{idVendor}=="2e8a", ATTRS{idProduct}=="0003", MODE="0666"

    # Raspberry Pi Debug Probe (CMSIS-DAP)
    SUBSYSTEM=="usb", ATTRS{idVendor}=="2e8a", ATTRS{idProduct}=="000c", MODE="0666"

    # Generic CMSIS-DAP probes (if you use a different debugger)
    SUBSYSTEM=="usb", ATTRS{idVendor}=="c251", ATTRS{idProduct}=="f000", MODE="0666"
  '';

  # TODO move to a boot module (include minegrub?)
  boot.loader.grub = {
    enable = true;
    default = "saved";
    useOSProber = true;

    efiSupport = true;
    device = "nodev";
  };

  # TODO move to a module for DroidCam
  boot.extraModprobeConfig = ''
    options v4l2loopback exclusive_caps=1 card_label="DroidCam"
  '';
  programs.droidcam.enable = true;

  # TODO move to SSH-host module
  services.openssh = {
    enable = true;
    openFirewall = true;
  };

  # Flatpaks are cool, I've only used like one, I think there is a way to nixify them
  services.flatpak.enable = true;

}
