export function generateTheme(colors) {
    let css = `/* Waybar Colors dynamically generated by WallRizz */\n`;

    css += `@define-color background ${colors.background};\n`;
    css += `@define-color foreground ${colors.foreground};\n`;
    css += `@define-color cursor ${colors.cursor};\n`;

    for (let i = 0; i < 16; i++) {
        css += `@define-color color${i} ${colors['color' + i]};\n`;
    }

    css += `@define-color text ${colors.foreground};\n`;
    css += `@define-color base ${colors.background};\n`;
    css += `@define-color red ${colors.color1};\n`;
    css += `@define-color green ${colors.color2};\n`;
    css += `@define-color yellow ${colors.color3};\n`;
    css += `@define-color blue ${colors.color4};\n`;
    css += `@define-color purple ${colors.color5};\n`;
    css += `@define-color aqua ${colors.color6};\n`;

    return css;
}

export function setTheme(newThemeConfigPath) {
    const cacheDir = HOME_DIR.concat("/.cache/wallrizz");
    const liveConfigPath = cacheDir.concat("/waybar.css");

    OS.exec(["mkdir", "-p", cacheDir]);

    const newThemeConfig = STD.loadFile(newThemeConfigPath);

    if (newThemeConfig && newThemeConfig.length > 0) {
        const file = STD.open(liveConfigPath, "w");
        if (file) {
            file.puts(newThemeConfig);
            file.close();

            try {
                OS.exec(["sh", "-c", "pkill -SIGUSR2 waybar > /dev/null 2>&1"]);
            } catch (e) {
                // If waybar is closed, it could give an error (I think) so, we go ahead and just ignore the fail
            }
        }
    }
}