export function generateThemeConfig(colors) {
    let css = "/* Waybar Colors dynamically generated by WallRizz */\n";

    css += "@define-color background " + (colors.background || "#282828") + ";\n";
    css += "@define-color foreground " + (colors.foreground || "#ebdbb2") + ";\n";
    css += "@define-color text " + (colors.foreground || "#ebdbb2") + ";\n";
    css += "@define-color base " + (colors.background || "#282828") + ";\n";

    for (let i = 0; i < 16; i++) {
        css += "@define-color color" + i + " " + (colors['color' + i] || "#ffffff") + ";\n";
    }

    css += "@define-color red " + (colors.color1 || "#fb4934") + ";\n";
    css += "@define-color green " + (colors.color2 || "#b8bb26") + ";\n";
    css += "@define-color yellow " + (colors.color3 || "#fabd2f") + ";\n";
    css += "@define-color blue " + (colors.color4 || "#83a598") + ";\n";
    css += "@define-color purple " + (colors.color5 || "#d3869b") + ";\n";
    css += "@define-color aqua " + (colors.color6 || "#8ec07c") + ";\n";

    return css;
}

export function setTheme(newThemeConfigPath) {
    const liveConfigPath = HOME_DIR.concat("/.cache/wallrizz/waybar.css");

    const newThemeConfig = STD.loadFile(newThemeConfigPath);

    if (newThemeConfig) {
        const file = STD.open(liveConfigPath, "w");
        if (file) {
            file.puts(newThemeConfig);
            file.close();
        }
    }
}