
// I was so tempted to write javadoc comments for this

// Creates a dynamically generated color theme (based after the catppuccin that this config originally used)
export function generateTheme(colors, isDark = true) {
    let css = "/* Waybar Colors dynamically generated by WallRizz */\n";
    css += "@define-color background " + (colors.background || "#282828") + ";\n";
    css += "@define-color foreground " + (colors.foreground || "#ebdbb2") + ";\n";
    css += "@define-color text " + (colors.foreground || "#ebdbb2") + ";\n";
    css += "@define-color base " + (colors.background || "#282828") + ";\n";

    // Standard 16 terminal colors
    for (let i = 0; i < 16; i++) {
        css += "@define-color color" + i + " " + (colors['color' + i] || "#ffffff") + ";\n";
    }

    // Basic Color Names
    css += "@define-color red " + (colors.color1 || "#fb4934") + ";\n";
    css += "@define-color green " + (colors.color2 || "#b8bb26") + ";\n";
    css += "@define-color yellow " + (colors.color3 || "#fabd2f") + ";\n";
    css += "@define-color blue " + (colors.color4 || "#83a598") + ";\n";
    css += "@define-color purple " + (colors.color5 || "#d3869b") + ";\n";
    css += "@define-color aqua " + (colors.color6 || "#8ec07c") + ";\n";

    // Mapping Wallrizz terminal colors to Catppuccin-style variable names
    css += "@define-color surface0 " + (colors.color8 || "#45475a") + ";\n";
    css += "@define-color surface1 " + (colors.color8 || "#585b70") + ";\n";
    css += "@define-color surface2 " + (colors.color8 || "#585b70") + ";\n";

    css += "@define-color overlay0 " + (colors.color8 || "#6c7086") + ";\n";
    css += "@define-color overlay1 " + (colors.color7 || "#7f849c") + ";\n";
    css += "@define-color overlay2 " + (colors.color7 || "#9399b2") + ";\n";

    css += "@define-color subtext0 " + (colors.color7 || "#a6adc8") + ";\n";
    css += "@define-color subtext1 " + (colors.color15 || "#bac2de") + ";\n";

    // Mapping accents
    css += "@define-color peach " + (colors.color3 || "#fab387") + ";\n";
    css += "@define-color flamingo " + (colors.color1 || "#f2cdcd") + ";\n";
    css += "@define-color sapphire " + (colors.color4 || "#74c7ec") + ";\n";
    css += "@define-color mauve " + (colors.color5 || "#cba6f7") + ";\n";
    css += "@define-color teal " + (colors.color6 || "#94e2d5") + ";\n";
    css += "@define-color maroon " + (colors.color1 || "#eba0ac") + ";\n";
    css += "@define-color pink " + (colors.color5 || "#f5c2e7") + ";\n";
    css += "@define-color rosewater " + (colors.color1 || "#f5e0dc") + ";\n";

    return css;
}

export function setTheme(newThemeConfigPath) {
    const cacheDir = HOME_DIR.concat("/.cache/wallrizz");
    const liveConfigPath = cacheDir.concat("/waybar.css");

    // Making the actual file that the stuff will be at
    OS.exec(["mkdir", "-p", cacheDir]);

    // Writing to the file
    const newThemeConfig = STD.loadFile(newThemeConfigPath);
    if (newThemeConfig) {
        const file = STD.open(liveConfigPath, "w");
        if (file) {
            file.puts(newThemeConfig);
            file.close();
            OS.exec(["pkill", "-SIGUSR2", "waybar"]);
        }
    }
}