function logMsg(msg) {
    try {
        const logPath = HOME_DIR.concat("/.cache/wallrizz/debug.log");
        const file = STD.open(logPath, "a"); // "a" is for append
        if (file) {
            file.puts(msg + "\n");
            file.close();
        }
    } catch (e) { }
}

export function getDarkThemeConf(colors) {
    logMsg("==== STARTING WAYBAR DARK PHASE ====");
    logMsg("Raw colors received: " + JSON.stringify(colors));
    try {
        const theme = generateTheme(colors, true);
        logMsg("Successfully ran generateTheme.");
        return generateWaybarConfig(theme);
    } catch (e) {
        logMsg("CRASH in getDarkThemeConf: " + e.message + " | Stack: " + e.stack);
        return "/* CRASHED */";
    }
}

export function getLightThemeConf(colors) {
    logMsg("==== STARTING WAYBAR LIGHT PHASE ====");
    try {
        const theme = generateTheme(colors, false);
        return generateWaybarConfig(theme);
    } catch (e) {
        logMsg("CRASH in getLightThemeConf: " + e.message);
        return "/* CRASHED */";
    }
}

export function setTheme(newThemeConfigPath) {
    logMsg("==== STARTING SET THEME PHASE ====");
    logMsg("Reading from temp path: " + newThemeConfigPath);

    try {
        const cacheDir = HOME_DIR.concat("/.cache/wallrizz");
        const liveConfigPath = cacheDir.concat("/waybar.css");

        OS.exec(["mkdir", "-p", cacheDir]);
        const newThemeConfig = STD.loadFile(newThemeConfigPath);

        if (!newThemeConfig) {
            logMsg("ERROR: loadFile returned nothing!");
            return;
        }

        logMsg("File read successfully. Length: " + newThemeConfig.length);

        if (newThemeConfig.indexOf("@define-color") !== -1) {
            logMsg("Valid CSS found. Writing to waybar.css...");
            const file = STD.open(liveConfigPath, "w");
            if (file) {
                file.puts(newThemeConfig);
                file.close();
                logMsg("Successfully wrote waybar.css!");
            } else {
                logMsg("ERROR: Failed to open waybar.css for writing.");
            }
        } else {
            logMsg("WARNING: Aborted write. Invalid text (probably Kitty config).");
        }

        OS.exec(["sh", "-c", "pkill -SIGUSR2 waybar > /dev/null 2>&1"]);
        logMsg("Reload signal sent to Waybar.");
    } catch (e) {
        logMsg("CRASH in setTheme: " + e.message + " | Stack: " + e.stack);
    }
}

function generateTheme(colorCodes, isDark = true) {
    const colors = colorCodes.map((c) => Color(c));
    const pickColor = (dark) => {
        const index = colors.findIndex((color) =>
            (dark ?? isDark) ? color.isDark() : color.isLight()
        );

        return index !== -1
            ? colors.splice(index, 1)[0]
            : isDark
                ? Color("black")
                : Color("white");
    };

    const background = pickColor();

    for (const color of colors) {
        while (!Color.isReadable(color, background)) {
            isDark ? color.saturate(1).brighten(1) : color.desaturate(1).darken(1);
        }
    }

    while (colors.length < 8) {
        colors.push(
            colors[Math.floor(Math.random() * colors.length)].analogous()[3],
        );
    }

    return Object.assign(
        {
            background,
            foreground: pickColor(false),
            cursor: pickColor(),
        },
        ...selectDistinctColors(colors, 8).map((color, i) => ({
            [`color${i}`]: color,
        })),
    );
}

function selectDistinctColors(colorObjects, count) {
    const sortedColors = colorObjects.sort((a, b) =>
        a.getBrightness() - b.getBrightness()
    );

    const selectedColors = [];
    while (selectedColors.length < count && colorObjects.length > 0) {
        if (selectedColors.length === 0) {
            const midIndex = Math.floor(sortedColors.length / 2);
            selectedColors.push(sortedColors[midIndex]);
            sortedColors.splice(midIndex, 1);
            continue;
        }

        let maxDistanceColor = null;
        let maxDistance = -1;

        for (let i = 0; i < sortedColors.length; i++) {
            const currentColor = sortedColors[i];
            const minDistance = Math.min(
                ...selectedColors.map((selected) =>
                    Color.readability(selected, currentColor)
                ),
            );

            if (minDistance > maxDistance) {
                maxDistance = minDistance;
                maxDistanceColor = currentColor;
            }
        }

        if (maxDistanceColor) {
            selectedColors.push(maxDistanceColor);
            sortedColors.splice(sortedColors.indexOf(maxDistanceColor), 1);
        } else {
            break;
        }
    }

    return selectedColors;
}

function generateWaybarConfig(theme) {
    const config = `/* Waybar Colors dynamically generated by WallRizz */
@define-color base ${theme.background.toHexString()};
@define-color mantle ${theme.color0.darken().toHexString()};
@define-color crust ${theme.color0.toHexString()};

@define-color text ${theme.foreground.toHexString()};
@define-color subtext0 ${theme.color7.toHexString()};
@define-color subtext1 ${theme.color15.toHexString()};

@define-color surface0 ${theme.color8.toHexString()};
@define-color surface1 ${theme.color8.lighten().toHexString()};
@define-color surface2 ${theme.color8.lighten().lighten().toHexString()};

@define-color overlay0 ${theme.color8.toHexString()};
@define-color overlay1 ${theme.foreground.toHexString()};
@define-color overlay2 ${theme.foreground.toHexString()};

@define-color blue ${theme.color4.toHexString()};
@define-color lavender ${theme.color4.toHexString()};
@define-color sapphire ${theme.color4.toHexString()};
@define-color sky ${theme.color6.toHexString()};
@define-color teal ${theme.color6.toHexString()};
@define-color green ${theme.color2.toHexString()};
@define-color yellow ${theme.color3.toHexString()};
@define-color peach ${theme.color3.toHexString()};
@define-color maroon ${theme.color1.toHexString()};
@define-color red ${theme.color1.toHexString()};
@define-color mauve ${theme.color5.toHexString()};
@define-color pink ${theme.color5.toHexString()};
@define-color flamingo ${theme.color1.toHexString()};
@define-color rosewater ${theme.color1.toHexString()};
`;
    return config;
}