
const HOME_DIR = OS.getenv("HOME");

export function generateTheme(colors) {
    try {
        let css = `/* Waybar Colors dynamically generated by WallRizz */\n`;

        css += `@define-color background ${colors.background || "#282828"};\n`;
        css += `@define-color foreground ${colors.foreground || "#ebdbb2"};\n`;
        css += `@define-color text ${colors.foreground || "#ebdbb2"};\n`;
        css += `@define-color base ${colors.background || "#282828"};\n`;

        for (let i = 0; i < 16; i++) {
            const colorHex = colors['color' + i] || "#ffffff";
            css += `@define-color color${i} ${colorHex};\n`;
        }

        css += `@define-color red ${colors.color1 || "#fb4934"};\n`;
        css += `@define-color green ${colors.color2 || "#b8bb26"};\n`;
        css += `@define-color yellow ${colors.color3 || "#fabd2f"};\n`;
        css += `@define-color blue ${colors.color4 || "#83a598"};\n`;
        css += `@define-color purple ${colors.color5 || "#d3869b"};\n`;
        css += `@define-color aqua ${colors.color6 || "#8ec07c"};\n`;

        return css;
    } catch (e) {
        return `/* Error parsing colors */\n`;
    }
}

export function setTheme(newThemeConfigPath) {
    const cacheDir = HOME_DIR.concat("/.cache/wallrizz");
    const liveConfigPath = cacheDir.concat("/waybar.css");

    try {
        OS.exec(["sh", "-c", "/run/current-system/sw/bin/mkdir -p " + cacheDir + " > /dev/null 2>&1"]);
    } catch (e) { }

    const newThemeConfig = STD.loadFile(newThemeConfigPath);

    if (newThemeConfig && newThemeConfig.length > 0) {
        const file = STD.open(liveConfigPath, "w");
        if (file) {
            file.puts(newThemeConfig);
            file.close();

            try {
                OS.exec(["sh", "-c", "/run/current-system/sw/bin/pkill -SIGUSR2 waybar > /dev/null 2>&1"]);
            } catch (e) { }
        }
    }
}