function generateTheme(colors, isDark = true) {
    const safeColors = Array.isArray(colors) ? colors : [];
    const getCol = (c, fallback) => {
        if (!c || String(c).trim() === "") return fallback;
        let clean = String(c).trim();
        return clean.startsWith('#') ? clean : '#' + clean;
    };

    const bg = safeColors[0];
    const fg = safeColors[1];
    const acc1 = safeColors[2];
    const acc2 = safeColors[3];
    const acc3 = safeColors[4];

    return `/* Waybar Colors dynamically generated by WallRizz */
@define-color base   ${getCol(bg, "#24273a")};
@define-color mantle ${getCol(bg, "#1e2030")};
@define-color crust  ${getCol(bg, "#181926")};
@define-color text     ${getCol(fg, "#cad3f5")};
@define-color subtext0 ${getCol(fg, "#a5adcb")};
@define-color subtext1 ${getCol(fg, "#b8c0e0")};
@define-color surface0 ${getCol(bg, "#363a4f")};
@define-color surface1 ${getCol(bg, "#494d64")};
@define-color surface2 ${getCol(bg, "#5b6078")};
@define-color overlay0 ${getCol(bg, "#6e738d")};
@define-color overlay1 ${getCol(fg, "#8087a2")};
@define-color overlay2 ${getCol(fg, "#939ab7")};
@define-color blue      ${getCol(acc1, "#8aadf4")};
@define-color lavender  ${getCol(acc1, "#b7bdf8")};
@define-color sapphire  ${getCol(acc1, "#7dc4e4")};
@define-color sky       ${getCol(acc2, "#91d7e3")};
@define-color teal      ${getCol(acc2, "#8bd5ca")};
@define-color green     ${getCol(acc2, "#a6da95")};
@define-color yellow    ${getCol(acc3, "#eed49f")};
@define-color peach     ${getCol(acc3, "#f5a97f")};
@define-color maroon    ${getCol(acc1, "#ee99a0")};
@define-color red       ${getCol(acc1, "#ed8796")};
@define-color mauve     ${getCol(acc3, "#c6a0f6")};
@define-color pink      ${getCol(acc3, "#f5bde6")};
@define-color flamingo  ${getCol(acc1, "#f0c6c6")};
@define-color rosewater ${getCol(acc1, "#f4dbd6")};
`;
}

function applyThemeDirectly(colors, isDark) {
    const css = generateTheme(colors, isDark);

    try {
        const cacheDir = HOME_DIR.concat("/.cache/wallrizz");
        const liveConfigPath = cacheDir.concat("/waybar.css");
        OS.exec(["mkdir", "-p", cacheDir]);

        const file = STD.open(liveConfigPath, "w");
        if (file) {
            file.puts(css);
            file.close();
        }

        OS.exec(["sh", "-c", "pkill -SIGUSR2 waybar > /dev/null 2>&1"]);
    } catch (e) {
    }

    return css;
}

export function getDarkThemeConf(colors) {
    return applyThemeDirectly(colors, true);
}

export function getLightThemeConf(colors) {
    return applyThemeDirectly(colors, false);
}

export function setTheme(newThemeConfigPath) {
    // intentionally blank
    return;
}