{ config, pkgs, ... }:

{
  nixpkgs.overlays = [
    (final: prev: {
      mathematica = prev.mathematica.override {
        source = prev.requireFile {
          name = "Wolfram_14.3.0_LIN_Bndl.sh";
          # Using the flat hash generated by nix-prefetch-url
          sha256 = "1xq3zrnglpxwlh6bkamzl9hpa913rxdwj1am0f8wnff651g1gxqn";
          message = ''
            Your override for Mathematica includes a different 
            src for the installer,
            and it is missing.
          '';
        };
      };
    })
  ];


  # Install the overlaid package
  environment.systemPackages = [
    pkgs.mathematica
  ];
}
