shell_integration no-rc

# Small chance that this is the wrong path
shell fish
# shell /nix/store/gdlvizwr80wwccx2v39h2as02rs0d1nb-fish-4.7.1/bin/fish


window_margin_width     5
background_tint         0.97
background_tint_gaps    -10.0
window_border_width     0pt


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME