# Set monitor and wallpaper
preload = /home/sa9m/Pictures/Wallpapers/Cars.jpg
preload = /home/sa9m/Pictures/Wallpapers/InDaWater.jpg
preload = /home/sa9m/Pictures/Wallpapers/Earth.png
preload = /home/sa9m/Pictures/Wallpapers/Revan.png
preload = /home/sa9m/Pictures/Wallpapers/Circle.png
preload = /home/sa9m/Pictures/Wallpapers/Wallpaper1.1.0.png
preload = /home/sa9m/Pictures/Wallpapers/BeachFriends.jpg
preload = /home/sa9m/Pictures/Wallpapers/MadeByMe/Wallpaper1.2.0.png
preload = /home/sa9m/Pictures/Wallpapers/Rivendell.png
preload = /home/sa9m/Pictures/Wallpapers/SwimmingHole.jpg
preload = /home/sa9m/Pictures/Wallpapers/ATrailInTheWoods.png
preload = /home/sa9m/Pictures/Wallpapers/FamilyHug.png
preload = /home/sa9m/Pictures/Wallpapers/SpiderGwen.png
preload = /home/sa9m/Pictures/Wallpapers/PurpleSpace.png
preload = /home/sa9m/Pictures/Wallpapers/AniVAhsoka.png
preload = /home/sa9m/Pictures/Wallpapers/OwlHouse.png
preload = /home/sa9m/Pictures/Wallpapers/ViAndPow.png
preload = /home/sa9m/Pictures/Wallpapers/Lumity.png
preload = /home/sa9m/Pictures/Wallpapers/TheOwlHouse.png
preload = /home/sa9m/Pictures/Wallpapers/WetFriends.jpg
preload = /home/sa9m/Pictures/Wallpapers/PrettyForest.png
preload = /home/sa9m/Pictures/Wallpapers/Pavement.jpg
preload = /home/sa9m/Pictures/Wallpapers/Friends!.jpg
preload = /home/sa9m/Pictures/Wallpapers/BrownieSleeping.jpg
preload = /home/sa9m/Pictures/Wallpapers/"Lock Screen"/GalaxyLock.png
wallpaper = eDP-1,/home/sa9m/Pictures/Wallpapers/Friends!.jpg
wallpaper = DP-5, /home/sa9m/Pictures/Wallpapers/BrownieSleeping.jpg
wallpaper = DP-7, /home/sa9m/Pictures/Wallpapers/WetFriends.jpg

# Optional: Set wallpaper style
# Options: stretch, fill, fit, center, tile
splash = false
