$base      = 0xff282828
$baseAlpha = 282828
$mantle    = 0xff1d2021
$crust     = 0xff161819

$text      = 0xffebdbb2
$subtext0  = 0xffa89984
$subtext1  = 0xffbdae93

$surface0  = 0xff3c3836
$surface1  = 0xff504945
$surface2  = 0xff665c54

$overlay0  = 0xff7c6f64
$overlay1  = 0xff928374
$overlay2  = 0xffa89984

$red       = 0xfffb4934
$green     = 0xffb8bb26
$yellow    = 0xfffabd2f
$blue      = 0xff83a598
$purple    = 0xffd3869b
$aqua      = 0xff8ec07c
$orange    = 0xfffe8019